const groceries = {
  vegetables: [
    "Carrots",
    "Broccoli",
    "Spinach",
    "Lettuce",
    "Tomatoes",
    "Bell Peppers",
    "Cucumbers",
    "Onions",
    "Potatoes",
    "Zucchini",
    "Green Beans",
    "Mushrooms",
    "Celery",
    "Garlic",
    "Cabbage",
  ],
  fruits: [
    "Apples",
    "Bananas",
    "Oranges",
    "Grapes",
    "Strawberries",
    "Blueberries",
    "Pineapple",
    "Watermelon",
    "Peaches",
    "Kiwi",
    "Mango",
    "Lemons",
    "Limes",
    "Berries",
    "Cherries",
    "Avocado",
    "Pears",
  ],
  meatProducts: [
    "Chicken Breast",
    "Ground Beef",
    "Pork Chops",
    "Salmon Fillets",
    "Bacon",
    "Sausages",
    "Turkey",
    "Steak",
    "Ham",
    "Lamb Chops",
    "Shrimp",
    "Tofu",
    "Ground Turkey",
    "Duck Breast",
  ],
  condiments: [
    "Ketchup",
    "Mustard",
    "Mayonnaise",
    "Soy Sauce",
    "BBQ Sauce",
    "Hot Sauce",
    "Ranch Dressing",
    "Italian Dressing",
    "Salsa",
    "Pesto",
    "Honey",
    "Maple Syrup",
    "Worcestershire Sauce",
    "Vinegar",
    "Olive Oil",
    "Coconut Oil",
    "Sesame Oil",
    "Peanut Butter",
    "Jam",
    "Hummus",
  ],
  others: [
    "Bread",
    "Milk",
    "Eggs",
    "Butter",
    "Cheese",
    "Yogurt",
    "Rice",
    "Pasta",
    "Cereal",
    "Flour",
    "Sugar",
    "Salt",
    "Pepper",
    "Coffee",
    "Tea",
    "Juice",
    "Soda",
    "Water",
    "Snacks",
    "Frozen Meals",
    "Ice Cream",
    "Chocolate",
    "Cookies",
    "Cake",
    "Soup",
    "Canned Goods",
  ],
};

// Desctiptions
const descriptions = {
  vegetables: [
    "Fresh and crunchy carrots, great for salads or snacking.",
    "Nutritious broccoli packed with vitamins and minerals.",
    "Tender spinach leaves, perfect for salads or cooking.",
    "Crisp and refreshing lettuce, ideal for salads and sandwiches.",
    "Juicy and flavorful tomatoes, versatile for various dishes.",
    "Sweet and crunchy bell peppers, great for adding color to meals.",
    "Cool and hydrating cucumbers, perfect for salads or pickling.",
    "A kitchen staple, versatile and essential for many recipes.",
    "Versatile and filling, great for roasting, mashing, or frying.",
    "Mild and tender zucchini, perfect for grilling or sautéing.",
    "Nutrient-rich green beans, delicious steamed or stir-fried.",
    "Earthy and flavorful mushrooms, great for soups or stir-fries.",
    "Crisp and crunchy celery, ideal for snacking or adding to salads.",
    "Pungent and aromatic garlic cloves, essential in many cuisines.",
    "Crisp and hearty cabbage, ideal for coleslaws or stir-fries.",
  ],
  fruits: [
    "Sweet and crunchy apples, perfect for snacking or baking.",
    "Creamy and nutritious bananas, a great source of potassium.",
    "Juicy and refreshing oranges, packed with vitamin C.",
    "Plump and juicy grapes, delicious eaten fresh or frozen.",
    "Deliciously sweet strawberries, great for desserts or smoothies.",
    "Antioxidant-rich blueberries, perfect for breakfast or baking.",
    "Tropical and sweet pineapple, great for desserts or cocktails.",
    "Refreshing and hydrating watermelon, ideal for hot days.",
    "Soft and velvety peaches, perfect for desserts or fruit salads.",
    "Exotic and tangy kiwi, delicious eaten fresh or in smoothies.",
    "Sweet and tropical mangoes, great for snacking or adding to salads.",
    "Zesty and tangy lemons, perfect for adding flavor to dishes or drinks.",
    "Bright and citrusy limes, ideal for cocktails or marinades.",
    "Mixed berries, a delicious and nutritious addition to any meal.",
    "Sweet and juicy cherries, perfect for snacking or desserts.",
    "Creamy and nutritious avocado, great for salads or spreads.",
    "Sweet and juicy pears, perfect for snacking or baking.",
  ],
  meatProducts: [
    "Lean and protein-rich chicken breast, versatile and easy to cook.",
    "Juicy and flavorful ground beef, perfect for burgers or meatballs.",
    "Tender and succulent pork chops, great for grilling or roasting.",
    "Rich and omega-3 packed salmon fillets, ideal for baking or grilling.",
    "Crispy and savory bacon, a delicious addition to any meal.",
    "Flavorful sausages, great for breakfast or grilling.",
    "Lean and protein-rich turkey, a healthier alternative to beef.",
    "Tender and juicy steak, perfect for grilling or pan-searing.",
    "Delicious and savory ham, ideal for sandwiches or holiday meals.",
    "Tender and flavorful lamb chops, great for grilling or roasting.",
    "Sweet and succulent shrimp, perfect for stir-fries or pasta dishes.",
    "Versatile and protein-rich tofu, great for vegetarian meals.",
    "Lean and protein-rich ground turkey, a healthier alternative to beef.",
    "Tender and succulent duck breast, perfect for special occasions.",
  ],
  condiments: [
    "Classic and tangy ketchup, perfect for burgers or fries.",
    "Sharp and tangy mustard, great for sandwiches or dressings.",
    "Creamy and rich mayonnaise, ideal for sandwiches or salads.",
    "Salty and savory soy sauce, essential in many Asian cuisines.",
    "Sweet and smoky BBQ sauce, perfect for grilled meats or ribs.",
    "Fiery and spicy hot sauce, great for adding heat to any dish.",
    "Creamy and tangy ranch dressing, perfect for salads or veggies.",
    "Flavorful and aromatic Italian dressing, great for salads or marinades.",
    "Chunky and spicy salsa, perfect for dipping or topping tacos.",
    "Fresh and aromatic pesto, ideal for pasta or sandwiches.",
    "Golden and sweet honey, perfect for sweetening drinks or desserts.",
    "Rich and flavorful maple syrup, great for pancakes or waffles.",
    "Savory and tangy Worcestershire sauce, essential in many recipes.",
    "Versatile and flavorful vinegar, perfect for dressings or marinades.",
    "Rich and fruity olive oil, ideal for cooking or drizzling on salads.",
    "Smooth and creamy coconut oil, great for cooking or baking.",
    "Nutty and aromatic sesame oil, perfect for Asian dishes or dressings.",
    "Creamy and delicious peanut butter, great for sandwiches or snacks.",
    "Sweet and fruity jam, perfect for spreading on toast or sandwiches.",
    "Creamy and flavorful hummus, perfect for dipping or spreading.",
  ],
  others: [
    "Soft and fluffy bread, essential for sandwiches or toast.",
    "Creamy and nutritious milk, perfect for cereal or baking.",
    "Protein-packed eggs, versatile and essential for many recipes.",
    "Rich and creamy butter, great for cooking or spreading on toast.",
    "Smooth and creamy cheese, perfect for sandwiches or cheese boards.",
    "Creamy and tangy yogurt, a delicious and nutritious snack.",
    "Versatile and filling rice, great as a side dish or main course.",
    "Nutritious and versatile pasta, perfect for countless dishes.",
    "Crunchy and delicious cereal, ideal for breakfast or snacking.",
    "Versatile and essential flour, perfect for baking bread or cakes.",
    "Sweet and versatile sugar, perfect for baking or sweetening drinks.",
    "Essential and flavorful salt, perfect for seasoning dishes.",
    "Freshly ground black pepper, ideal for adding flavor to any dish.",
    "Rich and aromatic coffee, perfect for starting your day.",
    "Classic and comforting tea, ideal for relaxing or warming up.",
    "Naturally sweet and refreshing juice, perfect for breakfast or snacks.",
    "Fizzing and refreshing soda, great for quenching your thirst.",
    "Pure and refreshing water, essential for hydration.",
    "Crunchy and satisfying snacks, perfect for on-the-go munching.",
    "Convenient and delicious frozen meals, ideal for quick dinners.",
    "Creamy and indulgent ice cream, perfect for dessert or a treat.",
    "Smooth and rich chocolate, great for snacking or baking.",
    "Sweet and crunchy cookies, perfect for dunking in milk or tea.",
    "Moist and delicious cake, ideal for celebrating special occasions.",
    "Comforting and flavorful soup, perfect for chilly days or when you're feeling under the weather.",
    "Convenient and versatile canned goods, perfect for stocking your pantry.",
  ],
};

// Prices

const prices = {
  vegetables: [
    1.99, 2.49, 1.79, 2.99, 1.59, 1.29, 2.19, 1.99, 2.79, 1.89, 1.99, 2.39,
    2.49, 1.69, 1.99,
  ],
  fruits: [
    0.99, 1.49, 1.29, 2.99, 1.99, 1.79, 2.49, 0.89, 1.59, 2.19, 1.99, 1.29,
    1.79, 1.99, 0.99,
  ],
  meatProducts: [
    3.99, 4.99, 5.49, 6.99, 7.49, 8.99, 9.99, 10.49, 11.99, 12.99, 13.49, 14.99,
    15.99, 16.99, 17.99,
  ],
  condiments: [
    2.99, 3.49, 1.99, 2.49, 2.99, 3.99, 1.49, 0.99, 3.99, 2.49, 2.99, 1.99,
    3.49, 3.99, 2.99,
  ],
  others: [
    1.99, 3.99, 2.49, 4.99, 5.99, 1.49, 2.99, 3.49, 4.49, 2.99, 3.99, 0.99,
    1.99, 2.99, 4.99,
  ],
};

module.exports = { groceries, descriptions, prices };
